version: "3.0"
services:
    swvl:
        build: .
        command: [ "node", "server.js" ]
        environment: 
            REDIS_URI: local:redis:6379
        ports: 
            - "4001:4001"
        depends_on: 
            - redis
    redis:
        image: redis:6.2-alpine
        command: ["redis-server", "--bind", "localhost", "--port", "6379"]
        environment: 
            - ALLOW_EMPTY_PASSWORD-yes
        ports: 
            - "6379:6379"
    redis-commander:
        container_name: redis-commander
        hostname: redis-commander
        image: rediscommander/redis-commander:latest
        restart: always
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - "8081:8081"
        # volumes: 
        #     - ./:/app